
package com.HotFactury.CWSFH.Prod;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.16
 * 2023-10-12T19:00:11.928-05:00
 * Generated source version: 3.1.16
 */

@WebFault(name = "EmisionTimbradoException", targetNamespace = "http://cfdi.ws4.facturehoy.certus.com/")
public class EmisionTimbradoException_Exception extends Exception {
    
    private com.HotFactury.CWSFH.Prod.EmisionTimbradoException emisionTimbradoException;

    public EmisionTimbradoException_Exception() {
        super();
    }
    
    public EmisionTimbradoException_Exception(String message) {
        super(message);
    }
    
    public EmisionTimbradoException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public EmisionTimbradoException_Exception(String message, com.HotFactury.CWSFH.Prod.EmisionTimbradoException emisionTimbradoException) {
        super(message);
        this.emisionTimbradoException = emisionTimbradoException;
    }

    public EmisionTimbradoException_Exception(String message, com.HotFactury.CWSFH.Prod.EmisionTimbradoException emisionTimbradoException, java.lang.Throwable cause) {
        super(message, cause);
        this.emisionTimbradoException = emisionTimbradoException;
    }

    public com.HotFactury.CWSFH.Prod.EmisionTimbradoException getFaultInfo() {
        return this.emisionTimbradoException;
    }
}
