package com.HotFactury.CWSFH.Prod;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2023-10-12T19:00:11.977-05:00
 * Generated source version: 3.1.16
 * 
 */
@WebServiceClient(name = "WsEmisionTimbrado40", 
                  wsdlLocation = "https://wsprod3.facturehoy.com/CFDI40/WsEmisionTimbrado40?wsdl",
                  targetNamespace = "http://cfdi.ws4.facturehoy.certus.com/") 
public class WsEmisionTimbrado40_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cfdi.ws4.facturehoy.certus.com/", "WsEmisionTimbrado40");
    public final static QName WsEmisionTimbrado40Port = new QName("http://cfdi.ws4.facturehoy.certus.com/", "WsEmisionTimbrado40Port");
    static {
        URL url = null;
        try {
            url = new URL("https://wsprod3.facturehoy.com/CFDI40/WsEmisionTimbrado40?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsEmisionTimbrado40_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://wsprod3.facturehoy.com/CFDI40/WsEmisionTimbrado40?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsEmisionTimbrado40_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsEmisionTimbrado40_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsEmisionTimbrado40_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WsEmisionTimbrado40_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsEmisionTimbrado40_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsEmisionTimbrado40_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WsEmisionTimbrado40
     */
    @WebEndpoint(name = "WsEmisionTimbrado40Port")
    public WsEmisionTimbrado40 getWsEmisionTimbrado40Port() {
        return super.getPort(WsEmisionTimbrado40Port, WsEmisionTimbrado40.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsEmisionTimbrado40
     */
    @WebEndpoint(name = "WsEmisionTimbrado40Port")
    public WsEmisionTimbrado40 getWsEmisionTimbrado40Port(WebServiceFeature... features) {
        return super.getPort(WsEmisionTimbrado40Port, WsEmisionTimbrado40.class, features);
    }

}
