package com.HotFactury.CWSFH.Prod;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2023-10-12T19:00:11.954-05:00
 * Generated source version: 3.1.16
 * 
 */
@WebService(targetNamespace = "http://cfdi.ws4.facturehoy.certus.com/", name = "WsEmisionTimbrado40")
@XmlSeeAlso({ObjectFactory.class})
public interface WsEmisionTimbrado40 {

    @WebMethod(operationName = "RecuperarAcuse")
    @Action(input = "http://cfdi.ws4.facturehoy.certus.com/WsEmisionTimbrado40/RecuperarAcuseRequest", output = "http://cfdi.ws4.facturehoy.certus.com/WsEmisionTimbrado40/RecuperarAcuseResponse")
    @RequestWrapper(localName = "RecuperarAcuse", targetNamespace = "http://cfdi.ws4.facturehoy.certus.com/", className = "com.certus.facturehoy.ws4.cfdi.RecuperarAcuse")
    @ResponseWrapper(localName = "RecuperarAcuseResponse", targetNamespace = "http://cfdi.ws4.facturehoy.certus.com/", className = "com.certus.facturehoy.ws4.cfdi.RecuperarAcuseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.HotFactury.CWSFH.Prod.WsResponseBO recuperarAcuse(
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        java.lang.String contrasenia,
        @WebParam(name = "UUID", targetNamespace = "")
        java.lang.String uuid
    );

    @WebMethod(operationName = "RecuperarAcuseCancelacion")
    @Action(input = "http://cfdi.ws4.facturehoy.certus.com/WsEmisionTimbrado40/RecuperarAcuseCancelacionRequest", output = "http://cfdi.ws4.facturehoy.certus.com/WsEmisionTimbrado40/RecuperarAcuseCancelacionResponse")
    @RequestWrapper(localName = "RecuperarAcuseCancelacion", targetNamespace = "http://cfdi.ws4.facturehoy.certus.com/", className = "com.certus.facturehoy.ws4.cfdi.RecuperarAcuseCancelacion")
    @ResponseWrapper(localName = "RecuperarAcuseCancelacionResponse", targetNamespace = "http://cfdi.ws4.facturehoy.certus.com/", className = "com.certus.facturehoy.ws4.cfdi.RecuperarAcuseCancelacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.HotFactury.CWSFH.Prod.WsResponseBO recuperarAcuseCancelacion(
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        java.lang.String contrasenia,
        @WebParam(name = "UUID", targetNamespace = "")
        java.lang.String uuid
    );

    @WebMethod(operationName = "EmitirTimbrar")
    @Action(input = "http://cfdi.ws4.facturehoy.certus.com/WsEmisionTimbrado40/EmitirTimbrarRequest", output = "http://cfdi.ws4.facturehoy.certus.com/WsEmisionTimbrado40/EmitirTimbrarResponse", fault = {@FaultAction(className = EmisionTimbradoException_Exception.class, value = "http://cfdi.ws4.facturehoy.certus.com/WsEmisionTimbrado40/EmitirTimbrar/Fault/EmisionTimbradoException")})
    @RequestWrapper(localName = "EmitirTimbrar", targetNamespace = "http://cfdi.ws4.facturehoy.certus.com/", className = "com.certus.facturehoy.ws4.cfdi.EmitirTimbrar")
    @ResponseWrapper(localName = "EmitirTimbrarResponse", targetNamespace = "http://cfdi.ws4.facturehoy.certus.com/", className = "com.certus.facturehoy.ws4.cfdi.EmitirTimbrarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.HotFactury.CWSFH.Prod.WsResponseBO emitirTimbrar(
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        java.lang.String contrasenia,
        @WebParam(name = "idServicio", targetNamespace = "")
        int idServicio,
        @WebParam(name = "xml", targetNamespace = "")
        byte[] xml
    ) throws EmisionTimbradoException_Exception;
}
